### ISSUE TITLE
Create bridge file for upper level axioms

### ISSUE THREAD

**Issue by caufieldjh** [berkeleybop/artificial-intelligence-ontology#105]
In lieu of including connections to upper level ontologies (e.g., BFO, IAO, maybe OBI) in the main release, we can produce a bridge file containing these.

**Comment by caufieldjh** [comment]
See: https://www.ebi.ac.uk/ols4/ontologies/obi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000011

**Comment by caufieldjh** [comment]
Or also COB, though that doesn't have its own unique IDs vs. OBI https://www.ebi.ac.uk/ols4/ontologies/cob/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCOB_0000082

**Comment by turbomam** [comment]
see example https://github.com/obophenotype/uberon/blob/master/src/ontology/bridge/cl-bridge-to-caro.owl
