### ISSUE TITLE
IDs are not CURIEs

### ISSUE THREAD

**Issue by caufieldjh** [berkeleybop/artificial-intelligence-ontology#109]
### Issue

Class IDs use the `https://w3id.org/aio/` prefix, and that's fine, except that the  intended `aio` prefix doesn't appear in artifacts.

### Release Version

2024-08-09

**Comment by caufieldjh** [comment]
See also #90

**Comment by cmungall** [comment]
Is this still an issue? Which artifacts do you mean?

**Comment by caufieldjh** [comment]
Probably a non-issue - will reopen if it poses problems anywhere
