### ISSUE TITLE
implement some defined classes to allow instances to be members of multiple categories

### ISSUE THREAD

**Issue by realmarcin** [berkeleybop/artificial-intelligence-ontology#123]
### Issue

We see the potential in this direction but for now we have decided to retain a single asserted hierarchy. Bias is also a new area of study.  Better not to assert two parents, potential future reasoning approach.

**Comment by cmungall** [comment]
What is an example of a term that should be classified under two categories?

**Comment by caufieldjh** [comment]
Closing; no changes needed for now
