### ISSUE TITLE
Ensure bridge ontology covers all classes

### ISSUE THREAD

**Issue by realmarcin** [berkeleybop/artificial-intelligence-ontology#126]
### Issue

one can read the upper bridge tsv that our entities in the AIO label class are subclasses of the obo id.  the obo label is provided as a convenience, no actions are taken during the ontology construction.  cell C2 in the tsv file 'SC %' robot language for 'make the thing on the far left sublclass of thing no far right'

**Comment by caufieldjh** [comment]
They are here: https://github.com/berkeleybop/artificial-intelligence-ontology/tree/main/src/ontology/bridge (this should be documented, however)

**Comment by cmungall** [comment]
This bridge file appears to be complete? Every AIO root is represented. So this issue can be closed? (perhaps after adding a link to the README)
