### ISSUE TITLE
move AIO gsheet into repo as tsv for arxiv submission

### ISSUE THREAD

**Issue by realmarcin** [berkeleybop/artificial-intelligence-ontology#49]
For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/artificial-intelligence-ontology)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by caufieldjh** [comment]
Do we also want to retain the robot template gsheet, or should the TSV in the repo be the single source of truth?

**Comment by caufieldjh** [comment]
OK, I think the consensus we reached was
* Keep the GSheet because it's easy to edit
* Check the GSheet into the repository as tsv
* Build using that GSheet as a ROBOT template; use OWL as component
