### ISSUE TITLE
From `runoak -i ../aio.owl annotate --text-file methods_reformat.txt > methods_reformat_output.txt`

### ISSUE THREAD

**Issue by turbomam** [berkeleybop/artificial-intelligence-ontology#66]
> WARNING:root:Using rdflib rdf/xml parser; this behavior may change in future
> WARNING:root:Not a curie: aio.owl
> WARNING:root:CURIE should not contain double colons: ['valid', 'for', 'go', 'annotation', 'extension']
> WARNING:root:CURIE should not contain double colons: ['valid', 'for', 'go', 'gp2term']
> WARNING:root:CURIE should not contain double colons: ['valid', 'for', 'go', 'ontology']
> WARNING:root:CURIE should not contain double colons: ['valid', 'for', 'gocam']
> WARNING:root:Not a curie: ro/subsets#ro-eco
> WARNING:root:Not a curie: ro.owl#z
> WARNING:root:Not a curie: ro.owl#y
> WARNING:root:Not a curie: ro.owl#x
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#p']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#q']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#x']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#y']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#z']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#u']
> WARNING:root:Not a curie: aio.owl
> WARNING:root:CURIE should not contain double colons: ['valid', 'for', 'go', 'annotation', 'extension']
> WARNING:root:CURIE should not contain double colons: ['valid', 'for', 'go', 'gp2term']
> WARNING:root:CURIE should not contain double colons: ['valid', 'for', 'go', 'ontology']
> WARNING:root:CURIE should not contain double colons: ['valid', 'for', 'gocam']
> WARNING:root:Not a curie: ro/subsets#ro-eco
> WARNING:root:Not a curie: ro.owl#z
> WARNING:root:Not a curie: ro.owl#y
> WARNING:root:Not a curie: ro.owl#x
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#p']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#q']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#x']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#y']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#z']
> WARNING:root:CURIE should not contain double colons: ['urn', 'swrl', 'var#u']
>

**Comment by caufieldjh** [comment]
???

**Comment by turbomam** [comment]
My thoughts exactly. I'm trying to refresh my memory now.
