### ISSUE TITLE
It does't look like we're following any rules for description dbxrefs

### ISSUE THREAD

**Issue by turbomam** [berkeleybop/artificial-intelligence-ontology#80]
We have a column with this header:

> ```
> Reference (DOI)
> >A oio:hasDbXref
> ```

And values like these

- https://en.wikipedia.org/wiki/Restricted_Boltzmann_machine
- GPT-4o with Sepalla et al. 2017
- https://en.wikipedia.org/wiki/Restricted_Boltzmann_machine|GPT-4o with Sepalla et al. 2017

### Questions
- Do we want the `|` to split a string into two dbxrefs?
- Are we allowing both URLs and unqualified strings? How would I know what "GPT-4o with Sepalla et al. 2017" means?

**Comment by turbomam** [comment]
These also create a "type = axiom" axioms. I don't think I have seen that in other ontologies, but I can't figure out why we're getting it.

**Comment by caufieldjh** [comment]
I think text like "GPT-4o with Sepalla et al. 2017" should be in a comment, while all other values should be URL or DOI

**Comment by turbomam** [comment]
They're all URLs now. Recommend closing.
