### ISSUE TITLE
we have asserted multi-heriarchies

### ISSUE THREAD

**Issue by turbomam** [berkeleybop/artificial-intelligence-ontology#85]
Neural Turing Machine Network  is a AIO:DeepFeedForwardNetwork and a AIO:LongShortTermMemory

**Comment by cmungall** [comment]
Yes, this was definitely is-a overloading

but fixed now

<img width="286" alt="image" src="https://github.com/user-attachments/assets/390339d2-c697-42bb-ac8f-041a22d7c29e">
