### ISSUE TITLE
Layer assignments to Networks have been lost?

### ISSUE THREAD

**Issue by realmarcin** [berkeleybop/artificial-intelligence-ontology#97]
For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/artificial-intelligence-ontology)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by turbomam** [comment]
asplenia?

**Comment by turbomam** [comment]
As of last night, I had done about half of them. I _suspect_ they weren't lost, but that you checked a class that I hadn't completed yet.

**Comment by turbomam** [comment]
I believe this can be closed.

**Comment by turbomam** [comment]
I think we need to work on our issue template
