### ISSUE TITLE
original descriptions moved to comments?

### ISSUE THREAD

**Issue by realmarcin** [berkeleybop/artificial-intelligence-ontology#98]
For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/artificial-intelligence-ontology)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by turbomam** [comment]
I don't understand how asplenia fits into this ontology

**Comment by caufieldjh** [comment]
it doesn't, that's just the issue template and he didn't replace it
